GameOfflineApi/GameOfflineApi/Controllers/AchievementController.cs
using GameOfflineApi.Models.EntityManagers;
using GameOfflineApi.Models.EntityManagers.Entities;
using GameOfflineApi.Models.ViewModels;
using System;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;

namespace GameOfflineApi.Controllers
{
    public class AchievementController : Controller
    {

        private DataContext context = new DataContext();

        // GET: Score
        public ActionResult Index(AchievementFilterInput input)
        {
            var list = context.Achievements.AsQueryable();
            if (!string.IsNullOrEmpty(input.Filter))
                list = list.Where(x => x.Name.ToLower().Contains(input.Filter.ToLower()));
            if (!string.IsNullOrEmpty(input.LevelName))
                list = list.Where(x => x.LevelName == input.LevelName);

            var count = list.Count();
            ViewBag.pages = Math.Ceiling((decimal)count / input.TakeCount);
            ViewBag.current = input;
            var model = list.OrderByDescending(x => x.Id).Skip((input.PageNumber - 1) * input.TakeCount).Take(input.TakeCount).ToList();
            ViewBag.games = context.Games;
            return View(model);
        }

        [HttpPost]
        public JsonResult AddOrUpdate(Achievement achievement)
        {
            try
            {
                if (achievement.Id == 0)
                {
                    context.Achievements.Add(achievement);
                }
                else
                {
                    context.Entry(achievement).State = EntityState.Modified;
                }
                context.SaveChanges();
                return Json(new { success = true }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception)
            {
                return Json(new { success = false }, JsonRequestBehavior.AllowGet);
            }
        }

        public JsonResult Get(int id)
        {
            var resultObj = context.Achievements.Find(id);
            resultObj.User = null;
            return Json(resultObj, JsonRequestBehavior.AllowGet);
        }
    }
}

GameOfflineApi/GameOfflineApi/Controllers/QuestionController.cs
using GameOfflineApi.Models.EntityManagers;
using GameOfflineApi.Models.EntityManagers.Entities;
using GameOfflineApi.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;

namespace GameOfflineApi.Controllers
{
    public class QuestionController : Controller
    {
        private DataContext context = new DataContext();

        public ActionResult Index(QuestionFilterInput input)
        {
            var list = context.Questions.Include(x => x.User);
            if (input.Active != null)
            {
                list = list.Where(x=> x.Active == input.Active.Value);
            }
            if (!string.IsNullOrEmpty(input.Filter))
            {
                list = list.Where(x => x.Content.ToLower().Contains(input.Filter.ToLower()));
            }
            var count = list.Count();
            ViewBag.pages = Math.Ceiling((decimal)count / input.TakeCount);
            ViewBag.current = input;
            var models = list.OrderByDescending(x=> x.Id).Skip((input.PageNumber - 1) * input.TakeCount).Take(input.TakeCount).ToList();
            return View(models);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            var model = context.Questions.Include(x=> x.Answers).FirstOrDefault(x=> x.Id == id);
            return View(model);
        }

        public JsonResult Edit(Question question)
        {
            try
            {
                context.Entry(question).State = EntityState.Modified;
                context.SaveChanges();
                return Json(new { success = true }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception)
            {
                return Json(new { success = false }, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

GameOfflineApi/GameOfflineApi/Controllers/UserController.cs
    using GameOfflineApi.Models.EntityManagers;
using GameOfflineApi.Models.EntityManagers.Entities;
using GameOfflineApi.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Data.Entity;
using System.Web;
using System.Web.Mvc;

namespace GameOfflineApi.Controllers
{
    public class UserController : Controller
    {
        private DataContext context = new DataContext();

        // GET: User
        public ActionResult Index(UserFilterInput input)
        {
            ViewBag.countAch = context.Achievements.Count();
            var ds = context.Users.Include(x=> x.Achievements).Include(x=> x.Scores);
            if (!string.IsNullOrEmpty(input.Filter))
            {
                ds = ds.Where(x=> x.Name.ToLower().Contains(input.Filter.ToLower()));
            }
            switch (input.OrderBy)
            {
                case 1:
                    if (input.Desc)
                        ds = ds.OrderByDescending(x => x.Name);
                    else
                        ds = ds.OrderBy(x=> x.Name);
                    break;
                case 2:
                    if (input.Desc)
                        ds = ds.OrderByDescending(x => x.Achievements.Count);
                    else
                        ds = ds.OrderBy(x => x.Achievements.Count);
                    break;
                default:
                    ds = ds.OrderByDescending(x=> x.Id);
                    break;
            }
            ViewBag.pages = Math.Ceiling((decimal)ds.Count()/input.TakeCount);
            ViewBag.current = input;
            var models = ds.Skip((input.PageNumber - 1) * input.TakeCount).Take(input.TakeCount).ToList();

            return View(models);
        }

        public ActionResult View(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            var model = context.Users.Include(x => x.Scores).Include(x => x.Achievements).FirstOrDefault(x=> x.Id == id);
            return View(model);
        }
    }
}

GameOfflineApi/GameOfflineApi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("styles", required: false)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Quản lý thông tin trò chơi", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Trang chủ", "Index", "Home")</li>
                    <li>@Html.ActionLink("Quản lý người dùng", "Index", "User")</li>
                    <li>@Html.ActionLink("Quản lý câu hỏi", "Index", "Question")</li>
                    <li>@Html.ActionLink("Quản lý thành tích", "Index", "Achievement")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        <div style="margin-top: 30px">
            @RenderBody()
        </div>
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>